spring:
  application:
    name: notification-service

  config:
    import: "optional:file:.env[.properties]"

  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://booksocial:booksocial@localhost:27017/booksocial?authSource=admin}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

server:
  port: 8087

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    issuer: booksocial-identity

management:
  endpoints:
    web:
      exposure:
        include: health