spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/booksocial
    username: booksocial
    password: booksocial

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

  security:
    oauth2:
      client:
        registration:
            google:
                client-id: 1011242572347-ejbkmmefs7f37i2tlsd118mlrbbop61a.apps.googleusercontent.com
                client-secret: ${GOOGLE_CLIENT_SECRET}

server:
  port: 8081

app:
  admin:
    email: admin@booksocial.com
    password: admin12345

  jwt:
    secret: o5sqlPeCocxouyW+l8fFpGrAaNUJ1m/dkXnpEb5YQjZqZd+m4vFtdPqwr0tcM2Zy
    access-token-ttl: 15m
    refresh-token-ttl: 7d
    issuer: booksocial-identity

  oauth2:
    frontend-redirect-uri: http://localhost:4200/oauth2/callback