spring:
  application:
    name: gateway

  config:
    import: "optional:file:.env[.properties]"

  threads:
    virtual:
      enabled: true

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: identity
              uri: ${IDENTITY_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/auth/**,/users/**

            - id: user-service
              uri: ${USER_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/profiles/**,/follows/**

            - id: book-service
              uri: ${BOOK_SERVICE_URI:http://localhost:8083}
              predicates:
                - Path=/books/**

            - id: review-service
              uri: ${REVIEW_SERVICE_URI:http://localhost:8084}
              predicates:
                - Path=/reviews/**

server:
  port: 8080

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    issuer: booksocial-identity

management:
  endpoints:
    web:
      exposure:
        include: health